# Generated by Django 2.2.4 on 2019-09-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptID', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interestID', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=30)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Deactive')])),
                ('password', models.TextField(max_length=255)),
                ('isTutor', models.PositiveIntegerField(choices=[(0, 'Student'), (1, 'Tutor')], default='')),
                ('isStudent', models.PositiveIntegerField(choices=[(0, 'Student'), (1, 'Tutor')], default='')),
                ('deptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ix_tutor.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ix_tutor.Interests')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ix_tutor.Users')),
            ],
        ),
    ]
